add async operation to retrieve the service picture
redux will complained as the action are making asynchronous operation, so we need to follow the pattern described on the following doc:
https://redux.js.org/advanced/async-actions
Error: Actions must be plain objects. Use custom middleware for async actions.